# replaymax_config.yaml
# Purpose: Explainable Replay Scoring + Strategic Variant Generator

version: "3.8.0"
compiled_for: "v3.8.0"

variant_generation_strategy:
  archetype_pool:
    - "Contrarian"
    - "Teacher"
    - "Investigator"
    - "Revealer"
    - "Confessor"
  variant_a:
    selection_rule: "Highest predicted engagement archetype"
  variant_b:
    selection_rule: "Opposing psychological archetype (not reworded version)"
  enforce_strategic_difference: true

replay_scoring_system:
  scoring_components:
    - hook_archetype_strength
    - replay_pacing_rhythm
    - emotional contrast
    - CTA triggering potential
    - novelty_factor
  score_range: [50, 100]
  rationale_output: true

rationale_formatting:
  output_template: |
    **ReplayMax Score:** {{score}}  
    **Reasoning:**  
    - Hook Archetype: {{archetype}}  
    - CTA Type: {{cta_type}}  
    - Emotional Glide: {{glide_quality}}  
    - Novelty Factor: {{novelty}}  
    - Strategic Advantage over Variant B: {{difference_explained}}

replay_trigger_conditions:
  when_to_activate:
    - "viewer retention drops after segment_2"
    - "emotional pacing flat across middle arc"
    - "thumbnail mismatch detected with CTA"
  override_logic:
    - "prioritize_variant_with_higher_novelty"
    - "adjust CTA position to align with hook intensity"

validation_tags:
  - "replaymax_explained_score"
  - "archetype_variant_difference"
  - "emotional_contrast_check"
  - "cta_alignment_verified"
  - "replay_trigger_logic"

variant_scoring:
  enabled: true
  weights:
    emotional_contrast: 0.5
    replay_trigger_strength: 0.3
    cta_novelty: 0.2
variants:
  limit: 2

# === PATCH: REPLAYMAX LOGIC v1.1 ===

variant_ranking_rules:
  scoring_criteria:
    - emotional_strength
    - punchline_impact
    - style_fusion_coherence
    - thumbnail_alignment
    - replay_trigger_quality
  scoring_method: "weighted_composite"
  variant_order: ["A", "B", "C", "D", "E"]

replaymax_fusion_sync:
  enabled: true
  behavior:
    - auto_rank_variants_based_on_topic_emotion
    - ensure_variant_a_is_most_replayable
    - prevent_conflict_with_style_hierarchy
  failsafe:
    - if_all_variants_similar: "trigger_punchline_remix"
    - if_style_clash_detected: "fallback_to_primary_style"
    
registered_modules:
  - replaymax_fusion_sync
  - variant_ranking_rules